steps:
- id: 'stage 1 terraform'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd Stage1
      export TF_VAR_project=$PROJECT_ID
      export TF_VAR_region=$_REGION
      export TF_VAR_pc_name=$_PC_NAME
      export TF_VAR_zone=$_REGION-$_ZONE
      echo ""
      echo "*************** TERRAFORM Stage 1 ******************"
      echo "******* At environment: $PROJECT_ID ********"
      echo "*************************************************"
      terraform init -backend-config="bucket=$_BUCKET_TFSTATE" || exit 1
      terraform plan || exit 1  
      terraform apply -auto-approve || exit 1
- id: 'credential to secret'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: ['./get-credential.sh']
  env:
  - 'LOCATION=${_REGION}-${_ZONE}'
  - 'REGION=$_REGION'
  - 'VCENTER_SECRET=$_VCENTER_SECRET'
  - 'NSX_SECRET=$_NSX_SECRET'
  - 'PC_NAME=$_PC_NAME'
  - 'VPC=$_VPC'
- id: 'Download Template'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '$_TEMPLATE', '.']
  waitFor: ['-']
- id: 'stage 2 terraform'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd Stage1
      export TF_VAR_project=$PROJECT_ID
      export TF_VAR_region=$_REGION
      export TF_VAR_pc_name=$_PC_NAME
      export TF_VAR_zone=$_REGION-$_ZONE
      export TF_VAR_nsxsecret=$_NSX_SECRET
      export TF_VAR_secret=$_VCENTER_SECRET
      export TF_VAR_ovfpath="/workspace/Bank-of-Anthos-V2.ova"
      echo ""
      echo "*************** TERRAFORM Stage 2 ******************"
      echo "******* At environment: $PROJECT_ID ****************"
      echo "****************************************************"
      terraform init -backend-config="bucket=$_BUCKET_TFSTATE" || exit 1
      terraform plan || exit 1  
      terraform apply -auto-approve || exit 1
timeout: 28800s
options:
  pool:
    name: 'projects/$PROJECT_ID/locations/europe-west6/workerPools/europe-west6'