steps:
- id: 'initial terraform'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      export TF_VAR_project=$PROJECT_ID
      export TF_VAR_region=$_REGION
      export TF_VAR_pc-name=$_PC_NAME
      export TF_VAR_zone=$_REGION-$_ZONE
      echo ""
      echo "*************** TERRAFORM INIT ******************"
      echo "******* At environment: $PROJECT_ID ********"
      echo "*************************************************"
      terraform init -backend-config="bucket=tf-state-vmware-explore" || exit 1
      terraform plan || exit 1  
      terraform apply -auto-approve || exit 1
- id: 'credential to secret'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: ['./get-credential.sh']
  env:
  - 'LOCATION=${_REGION}-${_ZONE}'
  - 'GCVE_REGION=$_GCVE_REGION'
  - 'VCENTER_SECRET=$_VCENTER_SECRET'
  - 'NSX_SECRET=$_NSX_SECRET'
  - 'PC_NAME=$_PC_NAME'
- id: 'Download Template'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://bank-of-anthos/.ova', '.']
  waitFor: ['-']
timeout: 28800s
